modLoader="javafml"
loaderVersion="[36,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/HaloOfBlocks/ProjectArsenal/issues"

[[mods]]
modId="projectarsenal"
version="development"
displayName="Project Arsenal"
updateJSONURL="https://raw.githubusercontent.com/HaloOfBlocks/ModVersions/main/projectarsenal/update.json?token=GHSAT0AAAAAABWZUTPEDDYUVOD3F64EIHN6Y3T74ZA"
displayURL="https://www.curseforge.com/minecraft/mc-mods/project-arsenal"
logoFile="icon.png"
credits="The community of Project Arsenal"
authors="Halo of Blocks Team: Autovw, CasualNoLifer"
description='''
A community project and add-on to MrCrayfish's Gun Mod
'''

[[dependencies.projectarsenal]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.projectarsenal]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.projectarsenal]]
    modId="cgm"
    mandatory=true
    versionRange="[1.2.6,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.projectarsenal]]
    modId="obfuscate"
    mandatory=true
    versionRange="[0.6.3,)"
    ordering="NONE"
    side="BOTH"

[modproperties.projectarsenal]
    catalogueImageIcon="icon.png"
    configuredBackground="minecraft:textures/block/anvil.png"
